### PR TITLE
Adds french language 

### PR DESCRIPTION
**Pull request by maxlefou**
As title says ☝️

### CODE REVIEW

**Comment by jreklund** [comment]
Hi, thanks for the translation. It looks like you committed all your files with CRLF (Windows) instead of LF (Linux). Can you convert both files into LR again. :-)

**Comment by maxlefou** [comment]
Good grief, i wanted to affinate a bit some french terms anyway.
This time it should be good and ready

**Comment by jreklund** [comment]
Um... now you have modified 49 files instead of two. Adding a empty line in some files and removing it other. Granted some are those already in the project are wrong (no PHP should end with ?>), but it's out of scope of this PR.

Either you roll back those changes or we can close this one and open a new PR. Sorry for the inconvenience.

**Comment by maxlefou** [comment]
know what, fuck this, i'm gonna start everything over

**Pull request closed without merging**
