### PR TITLE
Loan Enhancement

### PR DESCRIPTION
**Pull request by michael-kaufmann**
Added a Loanfilter and Loandata

### CODE REVIEW

**Comment by jreklund** [comment]
Hi, I can't seem to find any code for adding a filter in the sidebar. Have you forgot to commit those parts?

As of right now, most of the code are unnecessary. As it only are displaying the loan out data in one template.

**Comment by michael-kaufmann** [comment]
Hi, there are two commits. One adds the loan out data to the template, the other adds the Filter to the sidebar. Boths are visible to me in this pull request.

**Comment by jreklund** [comment]
You have added code to accept a filter, but not the filter itself. 
Can't find any changed made to tpl\default\movies\collection\sidebar.html.

**Comment by michael-kaufmann** [comment]
I made the changes at  /var/www/html/php4dvd/compiled/312e014df2cb5f6ed2b2db9c8e106be337d0ca7b_0.file.sidebar.html.php
Maybe the wrong location.

**Comment by michael-kaufmann** [comment]
Ah, got it, this is missing in the commit....  sorry, my first git post... I'll add it...

**Pull request closed without merging**
